export const initialStageDataList = [
  {
    id: "file-1",
    data: [
      {
        id: "vlJ-HWh6GwLBrgjfTiOP3",
        attrs: {
          name: "frame-target",
          "data-item-type": "frame",
          width: 1080,
          height: 1080,
          fill: "#ffffff",
          x: 200,
          y: 120,
          verticalAlign: "center",
          zIndex: 0,
          brightness: 0,
          "data-frame-type": "frame",
          id: "vlJ-HWh6GwLBrgjfTiOP3",
          align: "center",
          opacity: 1,
          rotation: 0,
          draggable: true,
          visible: true,
          scaleX: 1,
          scaleY: 1,
          offsetX: 0,
          offsetY: 0,
          skewX: 0,
          skewY: 0,
        },
        children: [],
      },
    ],
  },
];
